import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {createHash} from 'node:crypto';
import {readStats,updateStats,summarize,statFields,statText,chart} from '../dist/statistics.mjs';
const html=fs.readFileSync(new URL('../dist/index.html',import.meta.url),'utf8');
const model=html.slice(html.indexOf('function normalize('),html.indexOf('const battleplanMeta'));
const step=html.slice(html.indexOf('function stepGame('),html.indexOf('function renderScreen('));
const context={structuredClone,updateStats};vm.createContext(context);
// Extract actual production functions, not a duplicate implementation.
vm.runInContext(model.slice(0,model.indexOf('\nconst '))+step+';this.apply=apply;this.stepGame=stepGame;',context);
const catalogs={armies:['Nighthaunt','Seraphon'],battleplans:['Into the Fire'],tactics:['Blazing Onslaught','Smokescreen']};
const players=['Kay','Alex'].map((name,i)=>({name,faction:catalogs.armies[i],command:4,army:0,rage:0,fury:0,baseVictory:0,tactics:catalogs.tactics.map(name=>({name,goals:[0,0,0]}))}));
let r={players,game:{id:'old',battleplan:'Into the Fire',turn:0,phase:'-',active:0,starter:0,history:[]},revision:0};let seq=0;
const change=c=>({id:'event-'+(++seq),at:seq*1000,gameId:r.game.id,...c});
const run=c=>r=context.apply(r,c,context.stepGame,catalogs);
run(change({scope:'newGame',players:players.map(p=>({...p,tactics:catalogs.tactics})),battleplan:'Into the Fire'}));
assert.equal(readStats(r.game).events.length,0);assert.equal(r.players[0].command,4);
run(change({scope:'game',key:'advance',starter:1}));
const cp=change({scope:'player',player:0,key:'command',operation:'increment',delta:-1});run(cp);run(cp);
assert.equal(r.players[0].command,3);assert.equal(summarize(r).cpSpent[0],1,'Retry cannot double-count spending');
run(change({scope:'player',player:0,key:'victory',value:7}));
run(change({scope:'player',player:0,key:'goal',slot:0,goal:0,value:5}));
run(change({scope:'game',key:'advance'}));
assert.equal(r.game.active,2);assert.equal(readStats(r.game).segments.length,1);
run(change({scope:'player',player:1,key:'victory',value:15}));
run(change({scope:'player',player:1,key:'victory',value:10}));
let s=summarize(r,seq*1000+2000);
assert.deepEqual(s.cpSpent,[1,0]);assert.equal(s.race[0][1],12);assert.equal(s.race[1][1],10,'Race includes negative corrections');
assert.equal(s.bt[0][0],5);assert.equal(s.vp[0][0],7);assert.equal(s.leadChanges.length,2,'Counts actual lead swaps including correction');
assert.equal(s.totalTime[0],4000);assert.equal(s.totalTime[1],4000);
run(change({scope:'player',player:0,key:'goal',slot:0,goal:0,value:0}));
assert.equal(summarize(r).race[0][1],7,'Tactic untick corrects score');
run(change({scope:'game',key:'advance'}));run(change({scope:'game',key:'advance',starter:2}));
assert.equal(r.players[0].command,5,'Losing player gets extra CP in round two');
assert.equal(summarize(r).cpSpent[0],1,'Automatic CP refill is not spending');
run(change({scope:'game',key:'back'}));assert.equal(r.game.phase,'END');
assert.equal(summarize(r,seq*1000+10000).totalTime[0],summarize(r,seq*1000).totalTime[0],'END does not keep ticking');
for(const [label,field] of statFields){if(field.startsWith('stats-chart-'))assert(chart(field,r).includes('<svg'),label);else assert.notEqual(statText(field,r),'',label);}
const otherDevice=JSON.parse(JSON.stringify(r));assert.deepEqual(summarize(otherDevice,20000),summarize(r,20000),'OBS and another browser derive the same statistics');
const legacy=structuredClone(r);delete legacy.game.stats;legacy.game.phase='Top';legacy.game.turn=3;legacy.game.active=1;
const baseline=summarize(legacy,50000);assert.equal(baseline.race[0][4],7,'Existing game totals survive missing history');
run(change({scope:'newGame',players:players.map(p=>({...p,tactics:catalogs.tactics})),battleplan:'Into the Fire'}));assert.equal(summarize(r).cpSpent[0],0);assert.equal(summarize(r).totalTime[0],0);assert.equal(readStats(r.game).events.length,0);
assert.throws(()=>run({...cp,id:'stale',gameId:'not-this-game'}),/Another game/);
const gs=fs.readFileSync(new URL('../dist/Code.gs',import.meta.url),'utf8');
const digestContext={Utilities:{DigestAlgorithm:{SHA_256:'sha256'},Charset:{UTF_8:'utf8'},computeDigest:(algorithm,value)=>Array.from(createHash(algorithm).update(value).digest())}};
vm.createContext(digestContext);vm.runInContext(gs.slice(gs.indexOf('function sheetOutputHash_('))+';this.hash=sheetOutputHash_;',digestContext);
const longRecord=structuredClone(r);longRecord.game.stats='x'.repeat(200000);
assert.equal(digestContext.hash(longRecord).length,64,'Sheet export property stays small for a long game');
assert.equal(digestContext.hash(longRecord),digestContext.hash(r),'Statistics do not change visible Sheet export data');
console.log('Passed: transaction retries, score corrections, CP refills, timer transitions, shared reads, all OBS fields and new-game resets.');
